/*
 * Copyright (c) 2025 BekenCorp. All rights reserved.
 * 
 * This software is proprietary and confidential. No part of this software may be
 * reproduced, distributed, or transmitted in any form or by any means, including
 * photocopying, recording, or other electronic or mechanical methods, without the
 * prior written permission of BekenCorp, except in the case of brief quotations
 * embodied in critical reviews and certain other noncommercial uses permitted
 * by copyright law.
 * 
 * For permission requests, write to BekenCorp at armino_support@bekencorp.com.

 * Author: Beken LVGL Designer Tool
*/
/**
 * @file custom_func.c
 * @brief Custom Function Implementations
 * 
 * This file contains implementations for custom functions used in event handlers.
 * Generated by Beken LVGL Designer Tool.
 * 
 * Users should implement the function bodies according to their requirements.
 */

#include "custom_func.h"
#include "beken_ui.h"
#include "event_runtime.h"
#include "app_event.h"
#include "components/log.h"
#include "audio_engine_prompt_tone.h"
#include <stdio.h>

#define TAG "custom_func"
#define LOGI(...) BK_LOGI(TAG, ##__VA_ARGS__)
#define LOGW(...) BK_LOGW(TAG, ##__VA_ARGS__)

extern audio_engine_prompt_tone_handle_t g_audio_engine_prompt_tone;
extern unsigned char test1_mp3[];
extern unsigned int test1_mp3_len;

// add custom functions here
typedef enum {
    UI_MUSIC_STOPPED = 0,
    UI_MUSIC_PLAYING,
} ui_music_state_t;

static ui_music_state_t s_ui_music_state = UI_MUSIC_STOPPED;
static const char *s_ui_music_track = "test1.mp3";

static void ui_music_play_local_test1(void)
{
#if CONFIG_AE_SUPPORT_PROMPT_TONE && CONFIG_AE_PROMPT_TONE_SOURCE_ARRAY && CONFIG_AE_PROMPT_TONE_DECODER_MP3
    prompt_tone_uri_info_t ui_local_prompt_tone_info = {0};
    int ret;

    ui_local_prompt_tone_info.uri = (char *)test1_mp3;
    ui_local_prompt_tone_info.total_len = test1_mp3_len;
    ret = audio_engine_prompt_tone_start(g_audio_engine_prompt_tone, &ui_local_prompt_tone_info);
    if (ret != 0) {
        LOGW("ui local music play failed: %d\n", ret);
        return;
    }
    s_ui_music_state = UI_MUSIC_PLAYING;
    LOGI("ui local music play test1.mp3\n");
#else
    LOGW("ui local music requires prompt tone array + mp3 decoder\n");
#endif
}

void ui_music_play(void)
{
    ui_music_play_local_test1();
}

void ui_music_stop(void)
{
#if CONFIG_AE_SUPPORT_PROMPT_TONE
    int ret = audio_engine_prompt_tone_stop(g_audio_engine_prompt_tone);
    if (ret != 0) {
        LOGW("ui music stop playback failed: %d\n", ret);
    }
#else
    LOGW("prompt tone stop is disabled by config\n");
#endif
    s_ui_music_state = UI_MUSIC_STOPPED;
    LOGI("ui music stop\n");
}

void ui_music_next(void)
{
    ui_music_play_local_test1();
    LOGI("ui music next(test1.mp3)\n");
}

const char *ui_music_state_text(void)
{
    return (s_ui_music_state == UI_MUSIC_PLAYING) ? "播放中" : "已停止";
}

const char *ui_music_track_text(void)
{
    return s_ui_music_track;
}

