/*
 * Copyright (c) 2025 BekenCorp. All rights reserved.
 * 
 * This software is proprietary and confidential. No part of this software may be
 * reproduced, distributed, or transmitted in any form or by any means, including
 * photocopying, recording, or other electronic or mechanical methods, without the
 * prior written permission of BekenCorp, except in the case of brief quotations
 * embodied in critical reviews and certain other noncommercial uses permitted
 * by copyright law.
 * 
 * For permission requests, write to BekenCorp at armino_support@bekencorp.com.

 * Author: Beken LVGL Designer Tool
*/
/**
 * @file custom_func.c
 * @brief Custom Function Implementations
 * 
 * This file contains implementations for custom functions used in event handlers.
 * Generated by Beken LVGL Designer Tool.
 * 
 * Users should implement the function bodies according to their requirements.
 */

#include "custom_func.h"
#include "beken_ui.h"
#include "event_runtime.h"
#include "app_event.h"
#include "components/log.h"
#include "audio_engine_prompt_tone.h"
#include "test1_mp3_array.h"
#include <stdio.h>
#include <stdbool.h>

#define TAG "custom_func"
#define LOGI(...) BK_LOGI(TAG, ##__VA_ARGS__)
#define LOGW(...) BK_LOGW(TAG, ##__VA_ARGS__)

extern audio_engine_prompt_tone_handle_t g_audio_engine_prompt_tone;

// add custom functions here
typedef enum {
    UI_MUSIC_STOPPED = 0,
    UI_MUSIC_PLAYING,
} ui_music_state_t;

static ui_music_state_t s_ui_music_state = UI_MUSIC_STOPPED;
static const char *s_ui_music_track = "demo.mp3";
static const char *s_asr_demo_commands[4] = {
    "前进", "后退", "向左转", "向右转",
};
static const char *s_asr_demo_frames[4][4] = {
    {"  ^  ", " ^^ ", "^^^^", " ^^ "}, /* 前进 */
    {"  v  ", " vv ", "vvvv", " vv "}, /* 后退 */
    {"<    ", "<<   ", "<<<  ", "<<   "}, /* 左转 */
    {"    >", "   >>", "  >>>", "   >>"}, /* 右转 */
};
static int s_asr_demo_cmd_idx = 0;
static int s_asr_demo_frame_idx = 0;
static bool s_asr_demo_running = false;
static volatile int s_asr_demo_phrase_trigger = 0; /* 0:none, 1:nihaobotong, 2:zaijianbotong */
static char s_asr_demo_state[16] = "状态";
static char s_asr_demo_result[64] = "播放";

static void ui_music_play_local_test1(void)
{
#if CONFIG_AE_SUPPORT_PROMPT_TONE && CONFIG_AE_PROMPT_TONE_SOURCE_ARRAY && CONFIG_AE_PROMPT_TONE_DECODER_MP3
    prompt_tone_uri_info_t ui_local_prompt_tone_info = {0};
    int ret;

    ui_local_prompt_tone_info.uri = (char *)test1_mp3;
    ui_local_prompt_tone_info.total_len = test1_mp3_len;
    ret = audio_engine_prompt_tone_start(g_audio_engine_prompt_tone, &ui_local_prompt_tone_info);
    if (ret != 0) {
        LOGW("ui local music play failed: %d\n", ret);
        return;
    }
    s_ui_music_state = UI_MUSIC_PLAYING;
    LOGI("ui local music play demo.mp3\n");
#else
    LOGW("ui local music requires prompt tone array + mp3 decoder\n");
#endif
}

void ui_music_play(void)
{
    ui_music_play_local_test1();
}

void ui_music_stop(void)
{
#if CONFIG_AE_SUPPORT_PROMPT_TONE
    int ret = audio_engine_prompt_tone_stop(g_audio_engine_prompt_tone);
    if (ret != 0) {
        LOGW("ui music stop playback failed: %d\n", ret);
    }
#else
    LOGW("prompt tone stop is disabled by config\n");
#endif
    s_ui_music_state = UI_MUSIC_STOPPED;
    LOGI("ui music stop\n");
}

void ui_music_next(void)
{
    ui_music_play_local_test1();
    LOGI("ui music next(demo.mp3)\n");
}

const char *ui_music_state_text(void)
{
    return (s_ui_music_state == UI_MUSIC_PLAYING) ? "播放中" : "已停止";
}

const char *ui_music_track_text(void)
{
    return s_ui_music_track;
}

void ui_asr_demo_reset(void)
{
    s_asr_demo_cmd_idx = 0;
    s_asr_demo_frame_idx = 0;
    s_asr_demo_running = false;
    snprintf(s_asr_demo_state, sizeof(s_asr_demo_state), "状态");
    snprintf(s_asr_demo_result, sizeof(s_asr_demo_result), "播放");
}

void ui_asr_demo_execute(void)
{
    s_asr_demo_running = true;
    snprintf(s_asr_demo_state, sizeof(s_asr_demo_state), "识别中");
    snprintf(s_asr_demo_result, sizeof(s_asr_demo_result), "播放: %s", s_asr_demo_commands[s_asr_demo_cmd_idx]);
}

void ui_asr_demo_next_command(void)
{
    s_asr_demo_cmd_idx = (s_asr_demo_cmd_idx + 1) % 4;
    s_asr_demo_frame_idx = 0;
    s_asr_demo_running = false;
    snprintf(s_asr_demo_state, sizeof(s_asr_demo_state), "状态");
    snprintf(s_asr_demo_result, sizeof(s_asr_demo_result), "模式: %s", s_asr_demo_commands[s_asr_demo_cmd_idx]);
}

void ui_asr_demo_stop(void)
{
    s_asr_demo_running = false;
    snprintf(s_asr_demo_state, sizeof(s_asr_demo_state), "已停止");
    snprintf(s_asr_demo_result, sizeof(s_asr_demo_result), "停止");
}

void ui_asr_demo_anim_step(void)
{
    if (!s_asr_demo_running) {
        return;
    }
    s_asr_demo_frame_idx = (s_asr_demo_frame_idx + 1) % 4;
}

const char *ui_asr_demo_state_text(void)
{
    return s_asr_demo_state;
}

const char *ui_asr_demo_command_text(void)
{
    return s_asr_demo_commands[s_asr_demo_cmd_idx];
}

const char *ui_asr_demo_anim_text(void)
{
    if (!s_asr_demo_running) {
        return "  o  ";
    }
    return s_asr_demo_frames[s_asr_demo_cmd_idx][s_asr_demo_frame_idx];
}

const char *ui_asr_demo_result_text(void)
{
    return s_asr_demo_result;
}

void ui_asr_demo_notify_nihaobotong(void)
{
    s_asr_demo_phrase_trigger = 1;
}

void ui_asr_demo_notify_zaijianbotong(void)
{
    s_asr_demo_phrase_trigger = 2;
}

int ui_asr_demo_consume_phrase_trigger(char *phrase_buf, int phrase_buf_len)
{
    int trigger = s_asr_demo_phrase_trigger;

    if (phrase_buf == NULL || phrase_buf_len <= 0) {
        return 0;
    }
    if (trigger == 0) {
        return 0;
    }

    if (trigger == 1) {
        snprintf(phrase_buf, phrase_buf_len, "nihaobotong");
    } else if (trigger == 2) {
        snprintf(phrase_buf, phrase_buf_len, "zaijianbotong");
    } else {
        return 0;
    }

    s_asr_demo_phrase_trigger = 0;
    return 1;
}

